StudentMonitor/StudentMonitor/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentMonitor.Controllers
{
    public class LeaveController : Controller
    {
        // GET: Leave
        [HttpGet]
        public ActionResult ApplyLeave()
        {
            
            return View();

           
        }

        public ActionResult LeaveDetails()
        {
            StudentEntities2 leave = new StudentEntities2();
            int personId = Convert.ToInt32(Session["PersonId"]);
            var data = leave.LeaveDetails.Where(x => x.PersonId == personId).ToList();
            return View("_LeaveDetails",data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ApplyLeave(LeaveDetail leaveDetail)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (StudentEntities2 re = new StudentEntities2())
                    {
                        leaveDetail.PersonId = Convert.ToInt32(Session["PersonId"]);
                        leaveDetail.PersonName= Convert.ToString(Session["PersonName"]);
                         if (Convert.ToInt32(Session["Role"]) == 3)
                        {
                            leaveDetail.IsStudent = true;
                        }
                        else
                        {
                            leaveDetail.IsStudent = false;
                        }
                        leaveDetail.LeaveStatus = 1;
                        re.LeaveDetails.Add(leaveDetail);
                        re.SaveChanges();
                        ModelState.Clear();
                        ViewBag.Message = "Success";
                        leaveDetail = null;
                    }

                    
                }
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Student", "Index"));
            }
            return View(leaveDetail);
        }
    }
}

StudentMonitor/StudentMonitor/Controllers/LoginController.cs
using StudentMonitor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace StudentMonitor.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserProfile objUser)
        {
            if (ModelState.IsValid)
            {
                using (StudentEntities1 db = new StudentEntities1())  
                {
                    
                    var obj = db.UserProfiles.Where(a => a.UserName.Equals(objUser.UserName) && a.Password.Equals(objUser.Password)).FirstOrDefault();
                    if (obj != null)
                    {
                        Session["UserID"] = obj.UserId.ToString();
                        Session["UserName"] = obj.UserName.ToString();
                        Session["Name"] = obj.UserName.ToString();
                        Session["Role"] = obj.Role.ToString();
                        if (obj.Role.ToString() == "2")
                        {
                            using (StudentEntities5 re = new StudentEntities5())
                            {
                                var objTeacher = re.TEACHERS.Where(a => a.EMAIL.Equals(objUser.UserName)).FirstOrDefault();
                                Session["teacherClass"] = objTeacher.STD.ToString();
                                Session["teacherName"] = objTeacher.NAME.ToString();
                                Session["teacherId"] = objTeacher.TID.ToString();
                            }
                        }
                        return RedirectToAction("LandingPage");
                    }  
                }
            }
            return View(objUser);
        }

        public ActionResult LandingPage()
        {
            
            if (Session["UserID"] != null)
            {
                List<STUDENT> liStudent = new List<STUDENT>();
                List<STUDENT> liStu = null;
                using (StudentEntities4 student = new StudentEntities4())
                {
                    
                    liStu = student.STUDENTS.ToList();

                }
                if (Convert.ToInt32(Session["Role"]) == 3)
                {
                    string userName = Convert.ToString(Session["UserName"]);
                    liStudent = liStu.Where(a => a.EMAIL.Equals(userName.Trim())).ToList();

                    

                }
                else if (Convert.ToInt32(Session["Role"]) == 2)
                {
                    
                   
                        string teacherStd = Convert.ToString(Session["teacherClass"]);
                        List<string> liStd = teacherStd.Split(',').ToList();
                        foreach(string s in liStd)
                        {
                            liStudent.AddRange(liStu.Where(a => a.STD==s).ToList());
                        }

                    
                }

                    return View(liStudent);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Login");
        }

        public ActionResult Leave(string PersonId, string PersonName)
        {
            Session["PersonId"] = PersonId;
            Session["PersonName"] = PersonName;
            return RedirectToAction("ApplyLeave", "Leave");
        }
    }
}

StudentMonitor/StudentMonitor/Controllers/RegisterteacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentMonitor.Controllers
{
    public class RegisterteacherController : Controller
    {
        // GET: Registerteacher
        public ActionResult RegisterTeacher()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterTeacher(TEACHER obj)
        {
            try
            {
                UserProfile objUser = new UserProfile();
                if (ModelState.IsValid)
                {
                    using (StudentEntities5 re = new StudentEntities5())
                    {
                        re.TEACHERS.Add(obj);
                        re.SaveChanges();
                        ModelState.Clear();
                        objUser.UserName = obj.EMAIL;
                        objUser.Password = "teacherPwd";
                        objUser.Role = 2;
                        objUser.IsActive = true;
                        obj = null;
                        obj = null;
                        ViewBag.Message = "Success";
                    }
                    using (StudentEntities1 db = new StudentEntities1())
                    {
                        db.UserProfiles.Add(objUser);
                        db.SaveChanges();
                    }

                }

            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Student", "Index"));
            }

            return View(obj);
        }
    }
}

StudentMonitor/StudentMonitor/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace StudentMonitor.Controllers
{
    public class RegistrationController : Controller
    {
        public ActionResult RegisterStudent()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterStudent(STUDENT obj)
        {
            try
            {
                UserProfile objUser = new UserProfile();
                if (ModelState.IsValid)
                {
                    using (StudentEntities4 re = new StudentEntities4())
                    {
                        re.STUDENTS.Add(obj);
                        re.SaveChanges();
                        ModelState.Clear();
                        
                        objUser.UserName = obj.EMAIL;
                        objUser.Password = "studentPwd";
                        objUser.Role = 3;
                        objUser.IsActive = true;
                        obj = null;
                        ViewBag.Message = "Success";
                    }

                    

                    using (StudentEntities1 db = new StudentEntities1())
                    {
                       if(!db.UserProfiles.Any(x=>x.UserName == objUser.UserName))
                        {
                            db.UserProfiles.Add(objUser);
                            db.SaveChanges();
                        }
                        
                    }
                }
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Student", "Index"));
            }

            return View(obj);
        }
    }
}

StudentMonitor/StudentMonitor/Controllers/TimetablemainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentMonitor.Controllers
{
    public class TimetablemainController : Controller
    {
        // GET: Timetablemain
        public ActionResult Timetablemain()
        {
            StudentEntities8 tt = new StudentEntities8();
            var data = tt.sp_timetable1().ToList();
            return View(data);
        }

        public ActionResult TimeTable1(string standard)
        {
            StudentEntities8 tt = new StudentEntities8();
            var data = tt.sp_timetable1().Where(x => x.Standard == standard).ToList();
            ViewBag.timetable = data;

            return View("_TimeTable1");
        }
    }
}

StudentMonitor/StudentMonitor/Views/Login/LandingPage.cshtml
@model IEnumerable<StudentMonitor.STUDENT>
@{
    ViewBag.Title = "Home";
}




@{
    ViewBag.Title = "LandingPage";
    var grid = new WebGrid(source: Model, canPage: true, canSort: false);
}


<fieldset>
    <br />

    @if (@Session["Role"].Equals("1"))
    {

        <div class="jumbotron">
            <h1 class="display-3 text-warning">Welcome Admin!</h1>
            <br />

        </div>
        <div class="card text-white bg-success mb-3" style="width: 34em;float:left;">
            
            <div class="card-body">
                
                <p class="card-text">@Html.ActionLink("Register A Student", "RegisterStudent", "Registration", null, new { @style = "color:white" })</p>
            </div>
        </div>
        <div class="card text-white bg-info mb-3" style="width: 34rem;float:right;">
            
            <div class="card-body">
                
                <p class="card-text">@Html.ActionLink("Register A Teacher", "RegisterTeacher", "Registerteacher", null, new { @style = "color:white" })</p>
            </div>
        </div>
        @*@Html.Label("Welcome Admin") <br />
            @Html.ActionLink("Register A Student", "RegisterStudent", "Registration");<br />
            @Html.ActionLink("Register A Teacher", "RegisterTeacher", "Registerteacher");<br />
            @Html.ActionLink("Approve leaves", "ApproveLeaves", "Leave");<br />*@


    }
    else if (@Session["Role"].Equals("2"))
    {

        <div class="jumbotron">
            <h1 class="display-3 text-warning">Welcome Teacher!</h1>
            <br />

        </div>
        <h4 class="text-info">Student Details</h4>
        if (Model.Count() > 0)
        {
            @grid.GetHtml(
             htmlAttributes: new { id = "t01", @class = "table" },
             fillEmptyRows: false,
             mode: WebGridPagerModes.All,
             firstText: "<< First",
             previousText: "< Prev",
             nextText: "Next >",
             lastText: "Last >>",
             rowStyle: "table-active",
             alternatingRowStyle: "table-active",

             columns: new[] {
                grid.Column("SID", "Id"),
                grid.Column("NAME", "NAME"),
                grid.Column("STD", "CLASS"),
                grid.Column("AGE", "AGE"),
                grid.Column("ADDRESS", "ADDRESS")


             }
             )
        }

        <br />
        <div class="card text-white bg-success mb-3" style="width: 49%;float:left">
            <div class="card-body">
                <p class="card-text">@Html.ActionLink("View Timetable", "Timetablemain", "Timetablemain", null, new { @style = "color:white" })</p>
            </div>
        </div>
        <div class="card text-white bg-danger mb-3" style="width: 49%;float:right;">
            <div class="card-body">
                <p class="card-text"> @Html.ActionLink("Apply Leave", "Leave", "Login", new { PersonId = Convert.ToString(Session["teacherID"]), PersonName = Convert.ToString(Session["teacherName"]) }, new { @style = "color:white" })</p>
            </div>
        </div>
       

    }
    else if (@Session["Role"].Equals("3"))
    {
        <div class="jumbotron">
            <h1 class="display-3 text-warning">Welcome Parent!</h1>
            <br />

        </div>
        <h4 class="text-info">Student Details</h4>
        if (Model.Count() > 0)
        {
            @grid.GetHtml(
             htmlAttributes: new { id = "t01" ,@class="table"},
             fillEmptyRows: false,
             mode: WebGridPagerModes.All,
             firstText: "<< First",
             previousText: "< Prev",
             nextText: "Next >",
             lastText: "Last >>",
             rowStyle:"table-active",
             alternatingRowStyle: "table-active",

             columns: new[] {
                grid.Column("SID", "Id"),
                grid.Column("NAME", "NAME"),
                grid.Column("STD", "CLASS"),
                grid.Column("AGE", "AGE"),
                grid.Column("ADDRESS", "ADDRESS"),
                grid.Column("SID","Apply Leave",format: @<text><a class="text-warning" href="@Url.Action("Leave","Login",new{PersonId=item.SID,PersonName=item.NAME })">Apply Leave</a></text>)


                                                                                                                                                                                                                                                                                                      })
        }
        <br />
        <div class="card text-white bg-warning mb-3" style="width: 100%;float:right;">
            <div class="card-body">
                <p class="card-text">@Html.ActionLink("View Timetable", "Timetablemain", "Timetablemain", null, new { @style = "color:white" })</p>
            </div>
        </div>


    }

</fieldset>

StudentMonitor/StudentMonitor/Views/Login/Login.cshtml
@model StudentMonitor.UserProfile

@{
    ViewBag.Title = "Login";
}

    <body>
        @using (Html.BeginForm("Login", "Login", FormMethod.Post))
        {

            <fieldset>
                <br/><br/>
                <font size="5" >
                    <div class="page-header">Welcome To Student Tracking System</div>
                </font>
                <br/>
                <br/>
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @if (@ViewBag.Message != null)
                {
                    <div style="border: 1px solid red">
                        @ViewBag.Message
                    </div>
                }
                    <table>
                        <tr>
                            <td>@Html.LabelFor(a => a.UserName)&nbsp;</td>
                            <td>@Html.TextBoxFor(a => a.UserName, new { @class = "form-control form-control-sm" })</td>
                            <td>@Html.ValidationMessageFor(a => a.UserName)</td>
                        </tr>
                        <tr style="height:7px"></tr>
                        <tr>
                            <td>
                                @Html.LabelFor(a => a.Password)&nbsp;
                            </td>
                            <td>
                                @Html.PasswordFor(a => a.Password, new { @class = "form-control form-control-sm" })
                            </td>
                            <td>
                                @Html.ValidationMessageFor(a => a.Password)
                            </td>
                        </tr>
                        <tr style="height:7px"></tr>
                        <tr>
                            <td></td>
                            <td>
                                <input type="submit" value="Login" class="btn btn-primary" />

                            </td>
                            <td></td>
                        </tr>
                    </table>
            </fieldset>
        }

        </body>

StudentMonitor/StudentMonitor/Views/Login/UserDashBoard.cshtml
@{
    ViewBag.Title = "UserDashBoard";
}

< fieldset >
    < legend > User DashBoard < /legend>

< text >
    Welcome @Session["UserName"].ToString() < /text> 
     < /fieldset> 